### ISSUE TITLE
ffmpeg failure

### ISSUE THREAD

**Issue by JustCauseWhyNot** [zfleeman/ffmpeg4discord#32]
It's failing with this
```
❯ ff4d Videos/Replay/Replay_2024-11-16_19-54-39\ 1.mkv --config .config/ff4d/config.json -o Videos/Discord/pt14/16-airplanekill.webm
Performing first pass
frame=    0 fps=0.0 q=0.0 Lsize=N/A time=N/A bitrate=N/A speed=N/A    /A

Performing second pass
Traceback (most recent call last):
  File "/home/justcausewhynot/.local/share/ffmpeg4discord/env/bin/ff4d", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/home/justcausewhynot/.local/share/ffmpeg4discord/env/lib/python3.12/site-packages/ffmpeg4discord/__main__.py", line 97, in main
    twopass_loop(twopass=twopass, target_filesize=twopass.target_filesize, approx=approx)
  File "/home/justcausewhynot/.local/share/ffmpeg4discord/env/lib/python3.12/site-packages/ffmpeg4discord/__main__.py", line 16, in twopass_loop
    while twopass.run() >= target_filesize and not approx:
          ^^^^^^^^^^^^^
  File "/home/justcausewhynot/.local/share/ffmpeg4discord/env/lib/python3.12/site-packages/ffmpeg4discord/twopass.py", line 277, in run
    ffOutput.run(overwrite_output=True)
  File "/home/justcausewhynot/.local/share/ffmpeg4discord/env/lib/python3.12/site-packages/ffmpeg/_run.py", line 325, in run
    raise Error('ffmpeg', out, err)
ffmpeg._run.Error: ffmpeg error (see stderr output for detail)
```
output, and I don't know why.

**Comment by zfleeman** [comment]
Can you share your json and your video file (via Google drive or something if you feel up to it)

**Comment by zfleeman** [comment]
The output json code has only been merged to `main`. I need to make a PyPI release and have you pip update the package.

**Comment by JustCauseWhyNot** [comment]
You're right, but it shouldn't be responsible for the error right?

**Comment by zfleeman** [comment]
This would also be considered a correct format for your `-o` flag. I confirmed this on my local.

```bash
❯ ff4d Videos/Replay/Replay_2024-11-16_19-54-39\ 1.mkv --config .config/ff4d/config.json -o ./Videos/Discord/pt14/16-airplanekill.webm
```

We may be good, here. As an aside, this did help me find a [little bug](https://github.com/zfleeman/ffmpeg4discord/commit/713e0775c883a39046b742a7b40cbbc306592611) with assigning the output path via the --config option. Thanks!

**Comment by JustCauseWhyNot** [comment]
You're right. It was due to not supplying a full file path. I don't know why that's the first one to break that way. I've a lot of commands so far with different videos without specifying the full path without issue.
